config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :jsonapi } do
    namespace :v1 do
      resources :lists
      resources :tasks
      mount VandalUi::Engine, at: '/vandal'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'lists/:id/:slug', to: 'lists#show', as: :slugged_list
  #resources :lists do
    #resources :tasks, shallow: true
  #end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, inverse_of: :list
  accepts_nested_attributes_for :tasks, reject_if: :all_blank

  validates :name, presence: true
  def slug
    name.parameterize
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list, touch: true
  acts_as_list scope: :list

  validates :name, presence: true, allow_blank: true

  def completed=(was_completed)
    if was_completed
      self.completed_at = Time.now
    else
      self.completed_at = nil
    end
  end

  def new_position=(pos)
    insert_at(pos)
  end
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::API
      include Graphiti::Rails::Responders
    end
  end
end

app/controllers/api/v1/lists_controller.rb
module Api
  module V1
    class ListsController < Api::V1::ApiController
      def index
        lists = ListResource.all(params)

        if stale?(lists.data)
          respond_with(lists)
        end
      end

      def show
        list = ListResource.find(params)
        if stale?(list.data)
          respond_with(list)
        end
      end

      def create
        list = ListResource.build(params)

        if list.save
          render jsonapi: list, status: 201
        else
          render jsonapi_errors: list
        end
      end

      def update
        list = ListResource.find(params)

        if list.update_attributes
          render jsonapi: list
        else
          render jsonapi_errors: list
        end
      end

      def destroy
        list = ListResource.find(params)

        if list.destroy
          render jsonapi: { meta: {} }, status: 200
        else
          render jsonapi_errors: list
        end
      end

    end
  end
end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    class TasksController < ApiController
      def index
        tasks = TaskResource.all(params)
        respond_with(tasks)
      end

      def show
        task = TaskResource.find(params)
        respond_with(task)
      end

      def create
        task = TaskResource.build(params)

        if task.save
          render jsonapi: task, status: 201
        else
          render jsonapi_errors: task
        end
      end

      def update
        task = TaskResource.find(params)

        if task.update_attributes
          render jsonapi: task
        else
          render jsonapi_errors: task
        end
      end

      def destroy
        task = TaskResource.find(params)

        if task.destroy
          render jsonapi: { meta: {} }, status: 200
        else
          render jsonapi_errors: task
        end
      end

      def sideload_allowlist

      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def terms
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SharedTodoList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>

    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/_form.html.haml
= simple_form_for @list, validate: true, remote: true do |f|
  = f.input :name
  = f.button :submit, class: 'btn btn-primary', disable_with: 'Publishing...'

app/views/lists/_task_fields.html.haml
.nested-fields
  = f.input :name, input_html: { data: { controller: 'validation' } }
  = link_to_remove_association 'remove', f

app/views/lists/index.html.haml
%h1 Welcome to Shared Todo List
%h2 Create a todo list that you can quickly share with anyone
= link_to "Create a todo list", new_list_path

app/views/lists/new.html.haml
%h3 First, name your todo list:
= render 'form'

app/views/lists/new.js.erb
$('#new_list').replaceWith('<%= j render("form") %>')

app/views/lists/show.html.haml
.card
  .card-header.pt-3
    .row
      .col-7
        %h2.text-break= @list.name
      .col-5
        %button.btn.btn-primary.float-right
          Copy Link to List

  .card-body
    %ul#tasks.list-group-flush
      - @tasks.each do |task|
        = render task

  .card-footer
    = render partial: 'tasks/form', object:  @list.tasks.new

app/views/shared/_footer.html.erb
<footer class="footer text-muted bg-light">
  <div class="container">
    <span>© <%= Date.today.year %> James Castiglione</span>
    <ul class="list-inline mb-0 float-right">
      <li class="list-inline-item mr-3"><%= link_to "Source", 'https://github.com/jac241/shared_todo_list' %></li>
      <li class="list-inline-item mr-3"><%= link_to "Terms", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path %></li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <%= link_to 'Shared Checklist', root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/tasks/_form.html.haml
= simple_form_for [@list, @task], wrapper: :inline_form, validate: true,
  remote: true, html: { class: 'form-inline mb-2 mt-2' } do |f|
  = f.input :name, placeholder: 'Add task'

app/views/tasks/_task.html.haml
%li.list-group-item
  = task.name

app/views/tasks/create.js.erb
$('#tasks').append('<%= j render @task %>')
$('#new_task').find("input[type=text], textarea").val("")

app/views/tasks/new.js.erb
$('#new_task').replaceWith('<%= j render("form") %>')